import { Inter } from "next/font/google";
//import "./globals.css";

import Footer from "c:/Users/Asus/Desktop/WORK/msanext/src/app/components/footer"
import 'bootstrap/dist/css/bootstrap.css';
//import BootstrapClient from "."

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {children}
      <Footer/>
      </body>
    </html>

  );
}
